# Params related to model initialization & data preprocessing
# e.g. directly affecting the (inference) usage & behavior of the model
model_hparams:
  model_name: "i2c"
  model_suffix: "master"
  text_encoder_name: "clip"
  video_encoder_name: "clip_1frame"
  window_sec: 5.0
  target_fps: 10

# Params for the trainer
train_hparams:
  source_modality: "text"
  target_modalities:
    - "video"
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 0.12
  batch_size: 64
  max_epochs: 1000
  gpus: 8
  num_workers_for_dm: 4
  trainer_strategy: "ddp"
  freeze_modalities:
    - "video"
  path_load_pretrained_imu_encoder: ""
  path_load_from_checkpoint: ""
  lr: 0.00001
  split_number: 1
  use_egohos_best_pt: False
  test_only: True
  model_size: "SS"
  patch_size: 8
  save_imu_encoder: True
  source_index: 500