# Params related to model initialization & data preprocessing
# e.g. directly affecting the (inference) usage & behavior of the model
model_hparams:
  model_name: "i2c"
  model_suffix: "master"
  imu_encoder_name: "senvt"
  video_encoder_name: "clip_1frame"
  window_sec: 5.0
  target_fps: 10

# Params for the trainer
train_hparams:
  source_modality: "imu"
  target_modalities:
    - "video"
  limit_train_batches: 0.1
  limit_val_batches: 0.1
  limit_test_batches: 0.1
  batch_size: 64
  max_epochs: 10
  gpus: 8
  num_workers_for_dm: 4
  trainer_strategy: "ddp_find_unused_parameters_true"
  freeze_modalities:
    - "video"
  path_load_pretrained_imu_encoder: ""
  path_load_from_checkpoint: ""
  lr: 0.00001
  split_number: 1
  use_egohos_best_pt: False
  test_only: False
  model_size: "SS"
  patch_size: 8
  save_imu_encoder: False
  source_index: -1
  data_path: "../imu2clip-main/dataset/checkpoint/full_videos"